kind: Deployment
apiVersion: apps/v1
metadata:
  name: public-uaa-service
  namespace: t1cp-hpftes1-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-uaa-service
  template:
    metadata:
      labels:
        app: public-uaa-service
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        # istio----------------------------------------
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/proxyCPU: 600m
        sidecar.istio.io/proxyCPULimit: 600m
        sidecar.istio.io/proxyMemory: 1024Mi
        sidecar.istio.io/proxyMemoryLimit: 1024Mi
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
        # istio----------------------------------------
    spec:
      # volumes------------------------------------
      volumes:
        - name: cm-promtail-sidecar
          configMap:
            name: promtail-sidecar
            defaultMode: 420
        - name: shared-data
          emptyDir: { }
      # volumes------------------------------------
      containers:
        - name: public-uaa-service
          image: >-
            image-registry.openshift-image-registry.svc:5000/t1cp-hpftes1-ns/public-uaa-service:1.0.0
          resources:
            limits:
              cpu: 1100m
              memory: 4Gi
            requests:
              cpu: 1100m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          # livenessProbe--------------
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          # env----------------------------------------
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            # 日志路径(*)
            - name: SIDECAR_LOGFILE_PATH
              value: /tmp/log/
            # 日志路径(*)
            - name: HTTP_PROXY_HOST
            - name: HTTP_PROXY_PORT
            - name: HTTPS_PROXY
            - name: HTTP_PROXY
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_REDIS_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_REDIS_TIMEOUT
              value: "5000"
            - name: MANAGEMENT_ENDPOINT_HEALTH_GROUP_LIVENESS_EXCLUDE
              value: "redis"
            - name: MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE
              value: "redis"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          # volumeMounts----------------------------------------
          volumeMounts:
            - name: shared-data
              mountPath: /tmp/log/
          # volumeMounts----------------------------------------
          terminationMessagePolicy: File
        - name: promtail-sidecar
          image: 'registry.t11.caas.gcisdctr.hksarg:5000/grafana/promtail:latest'
          ports:
            - name: http-metrics
              containerPort: 1514
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: cm-promtail-sidecar
              mountPath: /etc/promtail
            - name: shared-data
              mountPath: /tmp/log/
          args:
            - '-config.file=/etc/promtail/promtail.yaml'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        # promtail container---------------------------------
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
