apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-sentinel-pv
  namespace: t1cp-hpftes1-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      type: local