apiVersion: v1
kind: Service
metadata:
  name: tes-redis-master-external
  namespace: t1cp-hpftes1-ns
  annotations:
    metallb.universe.tf/allow-shared-ip: "redis"
    metallb.universe.tf/loadBalancerIPs: "127.0.0.1"
spec:
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: tes-redis-a 