apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-c-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/redis-c"
  claimRef:
    namespace: t1cp-hpftes1-ns
    name: redis-c-pv