version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - /Users/wuzijie/document/docker-volumes/open-ui/data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
