version: '2'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf.d