version: '2'
services:
  mysql:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    image: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
