version: '2'
services:
  logstash:
    image: elastic/logstash:7.12.0-arm64
    container_name: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./config:/usr/share/logstash/config
    ports:
      - 5044:5044
      - 9600:9600
      - 4560:4560
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -Xss1m
      - TZ=Asia/Shanghai
